### PR TITLE
add Task model

### PR DESCRIPTION
**Pull request by sheldak**

### CODE REVIEW

**Comment by agga1** [comment]
parent_task_id - why simple integer? ->
maybe use parent = models.ForeignKey("self") ?
https://stackoverflow.com/questions/15285626/django-self-referential-foreign-key

**Comment by sheldak** [comment]
good idea, so I will change that

**Comment by agga1** [comment]
and task create method in serializer would be nice
https://www.django-rest-framework.org/api-guide/serializers/#saving-instances

**Comment by sheldak** [comment]
sure, so there will be commit with that in few minutes

**Review by agga1 — APPROVED** [review]
super

**Pull request merged**
